---
driver:
  name: vagrant
  vm_hostname: 'ftp.server.com'

provisioner:
  name: chef_zero


platforms:
- name: centos-6.9
- name: centos-7.4
- name: debian-7.11
  run_list: recipe[apt]
- name: debian-8.9
  run_list: recipe[apt]
- name: debian-9.2
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-16.04
  run_list: recipe[apt]

suites:
- name: default
  run_list:
    - recipe[onddo_proftpd_test::default]
- name: attrs
  run_list:
    - recipe[onddo_proftpd_test::attrs]
