---
driver:
  name: vagrant
  vm_hostname: ftp.server.com

provisioner:
  name: chef_zero


platforms:
- name: centos-6
- name: centos-7
- name: debian-8
  run_list: recipe[apt]
- name: debian-9
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-16.04
  run_list: recipe[apt]

suites:
- name: default
  run_list:
    - recipe[onddo_proftpd_test::default]
- name: attrs
  run_list:
    - recipe[onddo_proftpd_test::attrs]
