---
driver:
  name: vagrant
  vm_hostname: 'proftpd.local'

provisioner:
  name: chef_solo

platforms:
- name: centos-5.10
- name: centos-6.5
- name: centos-7.0
- name: fedora-19
- name: fedora-20
- name: debian-6.0.10
  run_list: ["recipe[apt]"]
- name: debian-7.6
  run_list: ["recipe[apt]"]
- name: ubuntu-10.04
  run_list: ["recipe[apt]"]
- name: ubuntu-12.04
  run_list: ["recipe[apt]"]
- name: ubuntu-14.04
  run_list: ["recipe[apt]"]

suites:
  - name: default
    run_list:
      - recipe[onddo_proftpd_test::default]
  - name: attrs
    run_list:
      - recipe[onddo_proftpd_test::attrs]
